pipeline {
    agent {
        dockerfile {
            filename './jenkins/Dockerfile' 
            args '-p 3000:3000'
            args '--tmpfs /.config'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') { 
            steps {
                sh 'npm install' 
            }
        }
        stage('Test') {
            steps {
                sh 'npm test'
            }
        }
        stage('Deliver') { 
            steps {
                // input message: 'Make suer everything is ok (Click "Proceed" to deploy to the production server)' 
                sshagent(credentials : ['abe0d167-e79b-49f2-b141-832e0f302786']) {
                    sh 'ssh -o StrictHostKeyChecking=no ubuntu@orderstaker.kevin-project.com sudo pm2 stop App'
                    sh 'scp -r -o StrictHostKeyChecking=no /var/jenkins_home/workspace/OrdersTakerBackEnd/package.json ubuntu@orderstaker.kevin-project.com:NodeFiles/'
                    sh 'scp -r -o StrictHostKeyChecking=no /var/jenkins_home/workspace/OrdersTakerBackEnd/src ubuntu@orderstaker.kevin-project.com:NodeFiles/'
                    sh 'ssh -o StrictHostKeyChecking=no ubuntu@orderstaker.kevin-project.com sudo npm i'
                    sh 'ssh -o StrictHostKeyChecking=no ubuntu@orderstaker.kevin-project.com sudo pm2 start src/App.js'
                }
            }
        }
    }
}