pipeline {
    agent {
        dockerfile {
            filename './jenkins/Dockerfile' 
            args '-p 3000:3000'
            args '--tmpfs /.config'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') { 
            steps {
                sh 'npm install' 
            }
        }
        stage('Test') {
            steps {
                sh 'npm test'
            }
        }
    }
}